#!/bin/bash

xdg_autostart() {
    local config=$1
    shopt -s nullglob
    if [[ -d "$config/autostart" ]]; then
        local i
        for i in $config/autostart/*.desktop; do
            grep -q -E "^Hidden=true" "$i" && continue
            if grep -q -E "^OnlyShowIn=" "$i"; then
                # need to test twice, as lack of the line entirely means we still run it
                grep -E "^OnlyShowIn=" "$i" | grep -q 'I3;' || continue
            fi
            grep -E "^NotShowIn=" "$i" | grep -q 'I3;' && continue

            local trycmd=$(grep -E "^TryExec=" "$i" | cut -d'=' -f2)
            if [[ -n "$trycmd" ]]; then
                which "$trycmd" >/dev/null 2>&1 || continue
            fi

            local cmd=$(grep -E "^Exec=" "$i" | cut -d'=' -f2)
            if [[ -n "$cmd" ]]; then
                $cmd &
            fi
        done
    fi
}

run_settings() {
    xset m 3.75 0 &
    xset -b &
    xsetroot -solid '#000000' &
}

run_autostart() {
    xdg_autostart "${XDG_CONFIG_DIRS-/etc/xdg}"
    xdg_autostart "${XDG_CONFIG_HOME-~/.config}"
}

run_screenlock() {
    xautolock -detectsleep -time 3 -locker 'i3lock -d -c 000000' \
              -notify 30 -notifier "notify-send -t 2000 'Locking screen in 30s'" &
}

run_settings
run_autostart
run_screenlock
