#!/bin/bash
xset m 3.75 0
xset -b
xsetroot -solid '#000000'

#qubes-manager
#qvm-run --all 'true'

autostart_etc=${XDG_CONFIG_DIRS-/etc/xdg}/autostart
autostart_home=${XDG_CONFIG_HOME-~/.config}/autostart

shopt -s nullglob
for i in $autostart_etc/*.desktop $autostart_home/*.desktop; do
	if ! grep -q "OnlyShowIn=" "$i"; then
		$(grep "Exec=" "$i" | sed 's/Exec=//') &
	fi
done

xautolock -detectsleep -time 3 -locker "i3lock -d -c 000000" \
          -notify 30 -notifier "notify-send -u critical -t 10000 -- 'Locking screen in 30s'" &

