#!/bin/sh
#i3status -c ~/.i3/status.conf | while true; do
#  read line
while true; do
  #names=`qvm-ls | grep ' \* ' | awk '{print $1}' | sort | grep -v '{dom0}\|{sys-.*}' | tr '\n' ' '`
  qubes=`qvm-ls | grep ' \* ' | wc -l`
  net=`qvm-run sys-net -p 'iwconfig; ifconfig' 2>/dev/null`
  quality=`echo "$net" | perl -ne 'print "$1 " if /Quality=([^ ]+)/'`
  ssid=`echo "$net" | perl -ne 'print $1 if /ESSID:"(.*)"/'`
  ip=`echo "$net" | perl -ne 'if (/^[w|e]/../^$/) { print $1 if /inet ([^ ]+)/ }'`
  date=`date '+%Y-%m-%d %H:%M:%S'`
  disk=`df -h / | tail -n 1 | awk '{print $4}'`
  load=`uptime | perl -ne 'print $1 if /load\s+average:\s+([^,]+)/'`
  ac=''
  [[ `cat /sys/class/power_supply/AC/online` == "1" ]] && ac=" AC"
  bat_now=`cat /sys/class/power_supply/BAT0/energy_now`
  bat_full=`cat /sys/class/power_supply/BAT0/energy_full_design`
  bat=$((100*bat_now/bat_full)) 
  wifi="$quality$ssid"
  if [[ "$wifi" == "" ]]; then wifi="none"; fi
  if [[ "$ip" == "" ]]; then ip="none"; fi
  echo "$qubes Q | W: $wifi | E: $ip | D: $disk | B: $bat%$ac | $load | $date" # | $line"
  sleep 5
done
