#!/bin/bash
id=$(xprop -root _NET_ACTIVE_WINDOW | sed 's/.*0x/0x/')
vm=$(xprop -id $id | grep '_QUBES_VMNAME(STRING)' | sed 's/.*"\(.*\)".*/\1/')
if [[ "$vm" != "" ]]; then
	qvm-run "$vm" urxvt
else
	xfce4-terminal
fi

#for terminal in $TERMINAL urxvt rxvt terminator Eterm aterm xterm gnome-terminal roxterm xfce4-terminal; do
#    if which $terminal > /dev/null 2>&1; then
#        exec $terminal
#    fi
#done

